version: 2
publish: &publish
  working_directory: ~/reactional
  docker:
    - image: circleci/node:12.16.2
  steps:
    - checkout

    - run:
        name: Installing dependencies
        command: yarn

    - run:
        name: Login into Expo
        command: yarn expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD

    - run:
        name: Publish to Expo Android
        command: yarn expo build:android -t app-bundle --release-channel $EXPO_RELEASE_CHANNEL

jobs:
  publish_to_expo_dev:
    environment:
      EXPO_RELEASE_CHANNEL: dev
    <<: *publish

  publish_to_expo_prod:
    environment:
      EXPO_RELEASE_CHANNEL: default
    <<: *publish

workflows:
  version: 2
  reactional:
    jobs:
      - publish_to_expo_dev:
          filters:
            branches:
              only: development
      - publish_to_expo_prod:
          filters:
            branches:
              only: master
